############################### redis 配置相关信息 #########################################
redis_port: 6379
dir: /var/lib/redis
redis_password: f447b20a7fcbf53a5d5be013ea0b15af
bind: 0.0.0.0


# 主从复制配置相关
# min-replicas-to-write: 3
# min-replicas-max-lag: 10

#限制redis服务使用的最大内存，超过阈值redis继续提供服务但是会报错。
maxmemory: 10GB
eviction: allkeys-lfu 


# 数据保存策略 生产系统 RDB AOF 混合模式。 默认 开启 aof-use-rdb-preamble yes
# RDB 保存时机
save: '3600 1 300 100 60 10000'
# aof 配置
appendonly: "yes"
appendfilename: "appendonly.aof"
appenddirname: "appendonlydir"
 #everysec always no 
appendfsync: everysec
# 重写 瘦身aof
no_appendfsync_on_rewrite: "no"
auto_aof_rewrite_percentage: 100
auto_aof_rewrite_min_size: 64mb
aof_load_truncated: "yes"
aof_use_rdb_preamble: "yes"
aof_timestamp_enabled: "no"
aof_rewrite_incremental_fsync: "yes"

################################## redis_sentinel 配置相关信息 ###############################
# 连接信息
master_node: 10.10.2.11
sentinel_port: 26379
master_groupname: mymaster001
# the quorum is only used to detect the failure
quorum: 2
replica_priority: 100
down_after_milliseconds: 1000*60
failover_timeout: 1000*180
parallel_syncs: 1

sentinel_dir: /var/lib/redis/