#if [ "`ls -A {{PG_DATA}}`" = "" ]; then if
############################################################
#        初始化 Replication 数据库                           #
############################################################
- name: create replication data on replication node   
  become_user: postgres
  # become_method: sudo
  shell: |
      export PGPASSWORD={{rep_password}} && pg_basebackup -h {{ replicaof }} -U {{ rep_user }} -F p -P -D {{ PG_DATA }} -r {{ rep_rate}} --checkpoint=fast -l postgresback_tea
  # when: need_init_replication_db|bool
  # register: backup_result

# - name: Show replication result
#   debug:
#     msg: "Replication INFO :  {{ backup_result}}"

############################################################
#        主备数据库物理复制槽                         #
############################################################
- name: replication | create pg physical replication slot
  postgresql_slot:
    name: "{{ application_name }}"
    slot_type: physical
    state: present
    port: 5432
  when: use_slot |bool
  delegate_to: "{{ replicaof }}"
  # run_once: true
  
## 没有使用 -R 参数自动生成。 自定义 recovery.conf 内容
- name: replication | create replication recovery.conf   
  template:
    src: recovery-{{PG_VERSION}}.conf.j2
    dest: "{{ PG_DATA }}/recovery.conf"
    owner: postgres
    group: postgres
    mode: 0644
  # when: need_init_replication_db|bool

- name: replication | start postgresql service
  systemd:  
    name: postgresql-{{PG_VERSION}}
    state: started
    enabled: true

- name: replication | wait for postgresql start
  wait_for: 
    port: 5432
    state: started
