- name: 配置 sentinel
  template: 
    src: sentinel.conf.j2
    dest: /etc/redis/sentinel.conf
    owner: redis
    group: redis

- name: 配置 users.acl
  file:
    path: /etc/redis/sentinel-users.acl
    state: touch
    owner: redis
    group: redis

- name: sentinel 启动服务
  service: 
   name: redis-sentinel
   state: restarted
   daemon_reload: yes
   enabled: true

- name: sentinel 等待服务启动成功
  wait_for:
   state: started
   port: "{{sentinel_port}}"

- name: sentinel 用户管理
  shell: |
    alias redis-cli="redis-cli --tls --cert /etc/redis/certs/redis.crt --key /etc/redis/certs/redis.key --cacert /etc/redis/certs/ca.crt "

    echo "ACL SETUSER default on >{{redis_password}}" | redis-cli -p {{sentinel_port}}
    echo "ACL SAVE" | redis-cli -p {{sentinel_port}} -a {{redis_password}} 
