scope: test
namespace: /pg/
name: pg01

restapi:
  listen: 10.10.2.11:8008
  connect_address: 10.10.2.11:8008
  authentication:
    username: puser
    password: p123456

ctl:
  insecure: true # Allow connections to Patroni REST API without verifying certificates

#--------------------------------------------------------------#
# log
#--------------------------------------------------------------#
log:
  level: INFO                           #  NOTEST|DEBUG|INFO|WARNING|ERROR|CRITICAL
  dir: /var/log/patroni                 #  patroni log dir
  file_size: 33554432                   #  32MB log triggers log rotation
  file_num: 20                          #  keep at most 30x32MB = 1GB log
  dateformat: '%Y-%m-%d %H:%M:%S %z'    #  IMPORTANT: discard milli timestamp
  format: '%(asctime)s %(levelname)s: %(message)s'

etcd3:
  #Provide host to do the initial discovery of the cluster topology:
  hosts: {{ etcd_hosts }}
  # username: 
  # password: 
  protocol: https
  cacert: 
  cert: 
  key: 

bootstrap:
  # this section will be written into Etcd:/<namespace>/<scope>/config after initializing new cluster
  # and all other cluster members will use it as a `global configuration`
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    primary_start_timeout: 300
    synchronous_mode: false
    failsafe_mode: true

    postgresql:
      use_pg_rewind: true

      parameters:
        wal_level: hot_standby
        hot_standby: "on"
        max_connections: 100
        max_worker_processes: 8
        wal_keep_segments: 8
        max_wal_senders: 10
        max_replication_slots: 10
        max_prepared_transactions: 0
        max_locks_per_transaction: 64
        wal_log_hints: "on"
        track_commit_timestamp: "off"
        # archive_mode: "on"
        # archive_timeout: 1800s
        # archive_command: /bin/true

postgresql:
#------------------------------------------------------------#
# how to connect to postgres
#------------------------------------------------------------#
#  bin_dir: 
  data_dir: '/var/lib/pgsql/10/data/'
  config_dir: '{/var/lib/pgsql/10/data/'
  pgpass: /var/lib/pgsql/.pgpass
  listen: 0.0.0.0:5432
  connect_address: 10.10.2.11:5432
  use_unix_socket: true # default: /var/run/postgresql, /tmp

  authentication:
    replication:
      username: replicator
      password: rep-pass
    superuser:
      username: postgres
      password: zalando
    rewind:  # Has no effect on postgres 10 and lower
      username: rewind_user
      password: rewind_password

    unix_socket_directories: '..'  # parent directory of data_dir

#watchdog:
#  mode: automatic # Allowed values: off, automatic, required
#  device: /dev/watchdog
#  safety_margin: 5

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
    version:  '10'