- name: install |  Setup PostgreSQL repository for {{ ansible_distribution }}
  become_user: root
  block:
  - name: Prepare PostgreSQL RPM
    copy: 
      src: "{{local_bin}}/postgresql/pgdg-redhat-repo-latest.noarch.rpm"
      dest: /tmp/

  - name: install |  Install PostgreSQL RPM
    package:
      name: /tmp/pgdg-redhat-repo-latest.noarch.rpm
      state: present
  when: ansible_os_family == "Redhat"

- name: install | Setup PostgreSQL repository for Debian 
  become_user: root
  block:
  - name: Prepare PostgreSQL Debian
    shell: | 
      echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list
      wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  # - name: apt-key
  - name: install |  update 
    apt:
      update_cache: yes
      ## 配置初始化数据库

  - name: install | postgresql-common 
    package: name=postgresql-common state=present

  - name: manu createcluster config 
    copy:  
      src: createcluster.conf
      dest: /etc/postgresql-common/createcluster.conf
    when: ansible_os_family == 'Debian'
