- hosts: "etcd"
  gather_facts: no
  tasks:
    - name:
      systemd: name=etcd state=stopped

    - name: migrate v2 to v3
      shell: | 
        export ETCDCTL_API=3 && \ 
        etcdctl migrate \
        --data-dir {{ ETCD_DATA_DIR }} \
        --wal-dir {{ ETCD_WAL_DIR }} \
        --cacert {{ ECTD_CERT_DIR }}/ca.pem \
        --cert {{ ECTD_CERT_DIR }}/etcd.pem \
        --key {{ ECTD_CERT_DIR }}/etcd-key.pem  

    - name: 启动 etcd 服务
      systemd: name=etcd state=restarted enabled=yes daemon_reload=yes

    - name: 等待 etcd 服务启动成功
      wait_for: host=127.0.0.1 port={{ ETCD_CLIENT_PORT }} state=started 