# Servers running a Linux operating system with a 5.x+ kernel, such as Red Hat Enterprise Linux (RHEL) 9 or Ubuntu LTS 20.04+

# https://min.io/docs/minio/kubernetes/upstream/operations/checklists/hardware.html#minio-hardware-checklist