---
- name: Tune kernel parameters
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    reload: yes
    ignoreerrors: yes
  notify: reload_sysctl
  with_dict: "{{ minio_tune_kernel_values }}"
  tags: tuning

- name: Selectively disable transparent huge pages
  shell: "echo madvise | tee /sys/kernel/mm/transparent_hugepage/enabled"
  tags: tuning

- name: Copy disk tuning script
  copy:
    src: minio_disk_tunning.sh
    dest: "/tmp/minio_disk_tunning.sh"
    # owner: "minio"
    # group: "minio"
    mode: 0755
  register: minio_copy_disk_tuning_script_result
  tags: tuning

- name: Run disk tuning
  command: "sh /tmp/minio_disk_tunning.sh"
  ignore_errors: true
  when: minio_copy_disk_tuning_script_result.changed
  tags: tuning
...