- name: repmgr | ensure repmgr pid file directory
  file:
    path: /run/repmgr/
    owner: "postgres"
    group: "postgres"
    mode: '0740'
    state: directory

- name: repmgr | create repmgr conf dir
  file:
    path: "{{ repmgr_conf_dir }}"
    owner: "postgres"
    group: "postgres"
    mode: '0740'
    state: directory
    recurse: true

- name: repmgr | create repmgr conf
  template:
    src: repmgr.conf.j2
    dest: "{{ repmgr_conf_dir }}/{{ repmgr_conf_file }}"
    owner: "postgres"
    group: "postgres"
    mode: '0740'
  notify: restart repmgrd
  register: repmgr_conf

- name: repmgr| failover_validation_command shell
  template: 
    src: failover_validation_command.sh.j2
    desc: /etc/repmgr/{{ postgres_release }}/failover_validation_command.sh
    owner: "postgres"
    group: "postgres"
    mode: '0755'

- name: repmgr | logrotate
  copy: 
    src: logrotate
    dest: /etc/logrotate.d/repmgr

- name: repmgr | repmgr_ctl alias 
  template:
    src: repmgr_ctl.sh.j2
    dest: /etc/profile.d/repmgr_ctl.sh
    mode: 0700
    owner: postgres
    group: postgres


# - name: PostgreSQL HBA 

# - name: Create repmgr user

# - name: Create repmgr database