# ETCD DCS 配置相关
CACERT: "{{CERT_LOCAL_BASE_DIR}}/{{ETCD_NAME}}/ca.pem"
ETCD_CLIENT_CERT: "{{CERT_LOCAL_BASE_DIR}}/{{ETCD_NAME}}/client-crt.pem"
ETCD_CLIENT_KEY: "{{CERT_LOCAL_BASE_DIR}}/{{ETCD_NAME}}/client-key.pem"

# 数据库配置
PG_PORT: 5432

# initdb -U 
SUP_USER: postgres 
#监控用户 pg_monitor
MON_USER: 'tea_mon'

PG_CONFIG: "{{ PG_DIR }}"
is_leader: false
clone_form: false

wal_log_hints: "on"
track_commit_timestamp: "off"
wal_level: logical
hot_standby: "on"

# PG_BIN: /usr/pgsql-14/bin/
#       /usr/lib/postgresql/@VERSION@/bin
# # 安装配置
# ###################### redhat
# pg_base_packages: 
#   - postgresql{{PG_VERSION}}-server
#   - postgresql{{PG_VERSION}}
#   - postgresql{{PG_VERSION}}-contrib
#   - postgresql{{PG_VERSION}}-libs

# pg_extends_packages:
#   - pg_repack_{{PG_VERSION}}
#   - python2-psycopg2

# ###################### debian
# pg_base_packages_debian:
#   - libpq-dev
#   - postgresql-client-{{PG_VERSION}}
#   - postgresql-{{PG_VERSION}}

# pg_extends_packages_debian:
#   - postgresql-{{PG_VERSION}}-postgis-3
#   - postgresql-{{PG_VERSION}}-repack

# pg_shared_preload_libs: 
#   - pg_repack
#   - pg_stat_statements
#   - auto_explain

sysctl:
  vm.swappiness = 1
  vm.dirty_background_ratio = 10
  vm.dirty_ratio = 40
  vm.dirty_expire_centisecs = 3000
  vm.dirty_writeback_centisecs = 500
  kernel.shmmax = 18446744073692700000
  kernel.shmall = 18446744073692700000
  kernel.shmmni = 4096
  kernel.sem = 250 512000 100 2048
  fs.file-max = 312139770
  fs.aio-max-nr = 1048576
  net.ipv4.ip_local_port_range = 2048 65499

  net.ipv4.tcp_tw_reuse = 1
  net.core.netdev_budget = 1024
  net.core.netdev_max_backlog = 2048
  net.core.rmem_default = 262144
  net.core.rmem_max = 4194304
  net.core.wmem_default = 262144
  net.core.wmem_max = 1048576
  kernel.panic_on_oops = 1

  kernel.numa_balancing = 0

  net.core.somaxconn = 4096

  net.ipv4.tcp_rmem = 4096 87380 16777216
  net.ipv4.tcp_wmem = 4096 65536 16777216
  net.ipv4.tcp_window_scaling = 1
  net.netfilter.nf_conntrack_max = 250000
  net.ipv4.tcp_max_syn_backlog=4096