CACERT: "{{CERT_LOCAL_BASE_DIR}}/{{ETCD_NAME}}/ca.pem"
ETCD_CLIENT_CERT: "{{CERT_LOCAL_BASE_DIR}}/{{ETCD_NAME}}/client-crt.pem"
ETCD_CLIENT_KEY: "{{CERT_LOCAL_BASE_DIR}}/{{ETCD_NAME}}/client-key.pem"

PG_PORT:5432

# initdb -U 
SUP_USER: postgres 
#监控用户 pg_monitor
MON_USER: 'tea_mon'

PG_CONFIG: "{{ PG_DIR }}"
is_leader: false
clone_form: false

wal_log_hints: "on"
track_commit_timestamp: "off"
wal_level: logical
hot_standby: "on"