## 为了更安全，每个服务创建独立证书及签名体系
- import_tasks: ca.yml 
  delegate_to: localhost
  run_once: true
  tags: always

## 服务证书，与服务器IP,DNS 绑定  
- import_tasks: san_cert.yml
  delegate_to: localhost
  tags: san_cert
  # when: only_common_cert == false

## 客户端证书
- import_tasks: client_cert.yml
  delegate_to: localhost
  run_once: true
  tags: client_cert
  # when: only_common_cert == false

## 通用证书
- import_tasks: common_cert.yml
  delegate_to: localhost
  run_once: true
  tags: common_cert
  # when: only_common_cert == true
