- name: Install required system packages
  apt:
    name: 
      - python3-pip
      - python3-virtualenv  # Explicitly install virtualenv
    state: present
  become: yes

- name: Create a virtual environment
  command: python3 -m venv /usr/local/venv
  args:
    creates: /usr/local/venv  # Ensures the command runs only if the venv doesn't exist

- name: Install requests package into the virtual environment
  pip:
    name: requests
    virtualenv: /usr/local/venv
