version: '2'
services:
      nginx:
        image: nginx
        restart: always
        hostname: nginx
        container_name: nginx
        privileged: true
        ports:
          - 808:80
        volumes:
          - ./conf/nginx.conf:/etc/nginx/nginx.conf
          - ./www/:/usr/share/nginx/html/
          - ./logs/:/var/log/nginx/
        logging:
          driver: loki
          options:
            loki-url: "http://10.10.2.13:3100/loki/api/v1/push"
            loki-retries: "5"
            loki-batch-size: "400"

