Vagrant.configure("2") do |config|
######################### ansible-controller node

  config.vm.define "controller" do |controller|
    controller.vm.box = "centos/7"
    controller.vm.hostname = "controller"
    controller.vm.network :private_network, ip: "10.10.2.10"
    controller.vm.provision "shell",
      inline: "sudo yum install ansible -y"
  end

######################### Cluster Nodes
  cluster_nodes=4

  (1..cluster_nodes).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.box = "centos/7"
      node.vm.hostname  = "node#{i}"
      node.vm.network :private_network, ip: "10.10.2.1#{i}"
      
  end
  end

##################### Setting CPU and Memory for All machines
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
    vb.cpus =  2
    #vb.disk :disk, name: "backup", size: "10GB"
  end

####################### Sharing Folder with machines
  config.vm.provision "shell", inline: <<-SHELL
     # set ssh root login with password vagrant
     sudo sed -i 's/#PermitRootLogin yes/PermitRootLogin yes/g' /etc/ssh/sshd_config
     sudo sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
     systemctl restart sshd
     # /data dir use separate disk block
    #  dd if=/dev/zero of=/var/loop.img bs=1M count=20480
    #  losetup /dev/loop0 /var/loop.img
    #  mkfs.xfs -f /dev/loop0
    #  mkdir /data
    #  mount /dev/loop0 /data
 
  SHELL

# config.disksize.size = '100GB'
end
