{
 "title": "实体机监控",
 "description": "CPU 内存 磁盘 IO 网络 温度等监控指标。https://github.com/starsliao/Prometheus",
 "tags": [ "instance" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d"
   },
   {
    "name": "idc",
    "label": "机房",
    "query": {
     "query": "label_values(node_exporter_build_info,idc)"
    }
   },
   {
    "name": "node",
    "label": "主机实例",
    "query": {
     "query": "label_values(node_exporter_build_info{idc=~'$idc'},instance)"
    }
   },
   {
    "name": "maxmount",
    "query": {
     "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}) by (mountpoint))))"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "基本信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "$idc  $node", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }, "repeat": "node" },
  {
   "title": "系统运行时间",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "CPU 核数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$node\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "内存总量",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "磁盘总空间",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes {instance=~\"$node\",fstype=~\"ext4|xfs\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "CPU使用率（5m）",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "CPU iowait（5m）",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[5m])) * 100"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100"
    }
   ]
  },
  {
   "title": "最大分区($maxmount)使用率",
   "type": "gauge",
   "description": "通过变量maxmount获取最大的分区。",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$node\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {instance=~\"$node\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"})"
    }
   ]
  },
  {
   "title": "当前打开的文件描述符",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "系统平均负载",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_1m"
    },
    {
     "expr": "node_load5{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_5m"
    },
    {
     "expr": "node_load15{instance=~\"$node\"}",
     "legendFormat": "{{instance}}_15m"
    }
   ]
  },
  {
   "title": "CPU使用率、磁盘每秒的I/O操作耗费时间（%）",
   "type": "graph",
   "description": "node_disk_io_time_seconds_total：\n磁盘花费在输入/输出操作上的毫秒数。该值为累加值。（Milliseconds Spent Doing I/Os）\n\nirate(node_disk_io_time_seconds_total[1m])：\n计算每秒的速率：(last值-last前一个值)/时间戳差值，即：1秒钟内磁盘花费在I/O操作的时间占比。",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}_System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}_User"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}_Iowait"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{instance}}_{{device}}_每秒I/O操作%"
    }
   ]
  },
  {
   "title": "各分区已使用空间",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}-node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext4|xfs\"}",
     "legendFormat": "{{mountpoint}}_使用空间"
    }
   ]
  },
  {
   "title": "各分区空间使用情况",
   "type": "table",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}"
    },
    {
     "expr": "1-(node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"})"
    }
   ]
  },
  {
   "title": "内存",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "内存信息",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
       "legendFormat": "{{instance}}_总内存"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemAvailable_bytes{instance=~\"$node\"}",
       "legendFormat": "{{instance}}_已用"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=~\"$node\"}",
       "legendFormat": "内存_Free"
      },
      {
       "expr": "node_memory_Buffers_bytes{instance=~\"$node\"}",
       "legendFormat": "内存_Buffers"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=~\"$node\"}",
       "legendFormat": "内存_Cached"
      },
      {
       "expr": "node_memory_MemAvailable_bytes{instance=~\"$node\"}",
       "legendFormat": "{{instance}}_可用"
      }
     ]
    },
    {
     "title": "Swap_内存",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_SwapFree_bytes{instance=~\"$node\"}",
       "legendFormat": "Swap_Free"
      },
      {
       "expr": "node_memory_SwapCached_bytes{instance=~\"$node\"}",
       "legendFormat": "SwapCached"
      },
      {
       "expr": "node_memory_SwapTotal_bytes{instance=~\"$node\"}",
       "legendFormat": "SwapTotal"
      }
     ]
    }
   ]
  },
  {
   "title": "网络",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "网络流量",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "bps", "label": "上传（-）/下载（+）" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{instance=~'$node',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[5m])*8",
       "legendFormat": "{{instance}}_{{device}}_in下载"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{instance=~'$node',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[5m])*8",
       "legendFormat": "{{instance}}_{{device}}_out上传"
      }
     ]
    },
    {
     "title": "TCP 连接情况",
     "type": "graph",
     "description": "CurrEstab - 当前状态为 ESTABLISHED 或 CLOSE-WAIT 的 TCP 连接数\n\nActiveOpens - 已从 CLOSED 状态直接转换到 SYN-SENT 状态的 TCP 平均连接数(1分钟内)\n\nPassiveOpens - 已从 LISTEN 状态直接转换到 SYN-RCVD 状态的 TCP 平均连接数(1分钟内)\n\nTCP_alloc - 已分配（已建立、已申请到sk_buff）的TCP套接字数量\n\nTCP_inuse - 正在使用（正在侦听）的TCP套接字数量\n\nTCP_tw - 等待关闭的TCP连接数",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{instance=~'$node'}",
       "legendFormat": "{{instance}}_ESTABLISHED"
      },
      {
       "expr": "node_sockstat_TCP_tw{instance=~'$node'}",
       "legendFormat": "{{instance}}_TCP_tw"
      },
      {
       "expr": "irate(node_netstat_Tcp_ActiveOpens{instance=~'$node'}[1m])",
       "legendFormat": "{{instance}}_ActiveOpens"
      },
      {
       "expr": "irate(node_netstat_Tcp_PassiveOpens{instance=~'$node'}[1m])",
       "legendFormat": "{{instance}}_PassiveOpens"
      },
      {
       "expr": "node_sockstat_TCP_alloc{instance=~'$node'}",
       "legendFormat": "{{instance}}_TCP_alloc"
      },
      {
       "expr": "node_sockstat_TCP_inuse{instance=~'$node'}",
       "legendFormat": "{{instance}}_TCP_inuse"
      }
     ]
    }
   ]
  },
  {
   "title": "读写",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "磁盘读写速率（IOPS）",
     "type": "graph",
     "description": "Reads completed: 每个磁盘分区每秒读完成次数\n\nWrites completed: 每个磁盘分区每秒写完成次数\n\nIO now 每个磁盘分区每秒正在处理的输入/输出请求数",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "iops", "label": "读取（-）/写入（+）I/O ops/sec" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{instance=~\"$node\"}[1m])",
       "legendFormat": "{{instance}}_{{device}}_读取"
      },
      {
       "expr": "irate(node_disk_writes_completed_total{instance=~\"$node\"}[1m])",
       "legendFormat": "{{instance}}_{{device}}_写入"
      }
     ]
    },
    {
     "title": "磁盘IO读写时间",
     "type": "graph",
     "description": "Read time ms 每个磁盘分区读操作花费的秒数\n\nWrite time ms 每个磁盘分区写操作花费的秒数\n\nIO time ms 每个磁盘分区输入/输出操作花费的秒数\n\nIO time weighted 每个磁盘分区输入/输出操作花费的加权秒数",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "s", "label": "读取（-）/写入（+）" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$node\"}[1m])",
       "legendFormat": "{{device}}"
      },
      {
       "expr": "irate(node_disk_io_time_weighted_seconds_total{instance=~\"$node\"}[1m])",
       "legendFormat": "{{device}}_加权"
      },
      {
       "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$node\"}[1m])",
       "legendFormat": "{{instance}}_{{device}}_读取"
      },
      {
       "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$node\"}[1m])",
       "legendFormat": "{{instance}}_{{device}}_写入"
      }
     ]
    },
    {
     "title": "r/s",
     "type": "graph",
     "description": "每秒读操作的次数=[Δrd_ios/Δt]",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_reads_completed_total{instance='$node'}[1m])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "w/s",
     "type": "graph",
     "description": "每秒写操作的次数=[Δwr_ios/Δt]",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(rate(node_disk_writes_completed_total{instance=\"$node\"}[1m]))",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "r_await",
     "type": "graph",
     "description": "每个读操作平均所需的时间=[Δrd_ticks/Δrd_ios]不仅包括硬盘设备读操作的时间，还包括了在kernel队列中等待的时间。",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(rate(node_disk_read_time_seconds_total {instance='$node'}[1m])) /(rate(node_disk_reads_completed_total {instance='$node'}[1m]))",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "w_await",
     "type": "graph",
     "description": "每个写操作平均所需的时间=[Δwr_ticks/Δwr_ios]不仅包括硬盘设备写操作的时间，还包括了在kernel队列中等待的时间。",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(rate(node_disk_write_time_seconds_total {instance='$node'}[1m])) /(rate(node_disk_writes_completed_total {instance='$node'}[1m]))",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "rMiB/s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "(rate(node_disk_read_bytes_total {instance='$node'}[1m]))",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "wKiB/s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "(rate(node_disk_written_bytes_total {instance='$node'}[1m]))",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "磁盘读写容量大小",
     "type": "graph",
     "description": "Read bytes 每个磁盘分区每秒读取的比特数\nWritten bytes 每个磁盘分区每秒写入的比特数",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "Bps", "label": "读取（-）/写入（+）" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{instance=~\"$node\"}[1m])",
       "legendFormat": "{{instance}}_{{device}}_读取"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{instance=~\"$node\"}[1m])",
       "legendFormat": "{{instance}}_{{device}}_写入"
      }
     ]
    },
    {
     "title": "%util",
     "type": "graph",
     "description": "该硬盘设备的繁忙比率=[Δio_ticks/Δt]表示该设备有I/O（即非空闲）的时间比率，不考虑I/O有多少，只考虑有没有",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
     "repeat": "idc",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_io_time_seconds_total{instance=\"$node\"}[1m])",
       "legendFormat": "{{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "温度",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "硬件温度",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "expr": "node_hwmon_temp_celsius{instance=~'$node'}",
       "legendFormat": "{{chip}}_{{sensor}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Raid 信息",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Raid 健康",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(node_md_is_active{instance=~\"$node\"}) / count(node_md_is_active{instance=~\"$node\"})"
      }
     ]
    },
    {
     "title": "Installed Disks",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_md_disks{instance=~\"$node\"}) / count(node_md_disks{instance=~\"$node\"})"
      }
     ]
    },
    {
     "title": "Active Disks",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(node_md_disks_active{instance=~\"$node\"}) / count(node_md_disks_active{instance=~\"$node\"})"
      }
     ]
    },
    {
     "title": "Block Sync Ratio",
     "type": "stat",
     "gridPos": { "h": 3, "w": 7, "x": 17, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(node_md_blocks_synced{instance=~\"$node\"}) / count(node_md_blocks_synced{instance=~\"$node\"})) / (sum(node_md_blocks{instance=~\"$node\"}) / count(node_md_blocks{instance=~\"$node\"}))"
      }
     ]
    },
    {
     "title": "Sync State",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(node_md_blocks{instance=~\"$node\"}) / count(node_md_blocks{instance=~\"$node\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(node_md_blocks_synced{instance=~\"$node\"}) / count(node_md_blocks_synced{instance=~\"$node\"})",
       "legendFormat": "Synced"
      }
     ]
    }
   ]
  }
 ]
}