- name: install | Install PostgreSQL Service
  package: name={{ item }} state=present
  with_items:
    - '{{ pg_base_packages }}'
  register: install_postgresql

- name: install | Install PostgreSQL Base Extensions Packages
  package: name={{ item }} state=present
  with_items:
    - '{{ pg_extends_packages }}'
  
- name: install | make postgres data dir
  file:
    path: "{{PG_DATA}}"
    state: directory
    owner: postgres
    group: postgres
    mode: 0700

- name: install | make postgres log dir
  file:
    path: "/var/log/postgresql/"
    state: directory
    owner: postgres
    group: postgres
    mode: 0700

- name: install | Prepare Config PostgreSQL Serivice 
  file:
    path: /etc/systemd/system/postgresql-{{PG_VERSION}}.service.d
    state: directory

- name: install | Config PostgreSQL Serivice 
  template:
    dest: /etc/systemd/system/postgresql-{{PG_VERSION}}.service.d/pg_override.conf
    src: pg_override.conf.j2

- name: install pg | Make certs dir
  file:
    path: /etc/postgres/certs/
    state: directory
    owner: postgres
    group: postgres
  
- name: 颁发证书
  copy:
    dest: /etc/ssl/certs/{{ item.to }}
    src: "{{ CERT_LOCAL_DIR }}/{{ item.from }}"
    mode: 0600
    owner: postgres
    group: postgres
  with_items: 
    - { from: ca.pem, to: ca.crt }
    - { from: common-key.pem , to: server.key }
    - { from: common-crt.pem , to: server.crt }


