- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- import_tasks: pre_install.yml

- import_tasks: install_pg.yml

- import_tasks: install_patroni.yml

- import_tasks: pg_exporter.yml

- import_tasks: monitor.yml