- name: install |  Setup PostgreSQL repository for {{ ansible_distribution }}
  become_user: root
  block:
  - name: Prepare PostgreSQL RPM
    copy: 
      src: "{{local_bin}}/postgresql/pgdg-redhat-repo-latest.noarch.rpm"
      dest: /tmp/

  - name: install |  Install PostgreSQL RPM
    package:
      name: /tmp/pgdg-redhat-repo-latest.noarch.rpm
      state: present
  when: ansible_distribution == "CentOS"

- name: 颁发证书
  copy:
    dest: /etc/postgres/certs/{{ item.to }}
    src: "{{ CERT_LOCAL_DIR }}/{{ item.from }}"
    mode: 0600
    owner: postgres
    group: postgres
  with_items: 
    - { from: ca.pem, to: ca.crt }
    - { from: common-key.pem , to: server.key }
    - { from: common-crt.pem , to: server.crt }