# become_user: postgres
---
### 远程下载安装包对网络环境有依赖 ， 后期考虑搭建私有镜像仓库
###

- name: install pgdg rpm
  become_user: root
  block:
    - name: "get url"
      shell: |
        curl https://install.citusdata.com/community/rpm.sh | sudo bash
   
- name: 安装citus
  yum: 
    name: citus110_14.x86_64
    state: present

- name: Ensure Postgres is configured.
  block:
    - name: 创建自定义配置
      shell: |
        if grep -q 'citus' /var/lib/pgsql/14/data/postgresql.conf; then
            printf "\033[0;33m[WARN] citus already set, skip  \033[0m\n" >&2
          else # 首次配置
            echo "shared_preload_libraries = 'citus'" >> /var/lib/pgsql/14/data/postgresql.conf
        fi
      notify: restart postgres

- name: restart postgres
  service: "name=postgresql-14 state=started enabled=yes"