rep_rate: 100M
# pg_role: master
use_slot: false

#bgwriter
#WAL，
#checkpoint
#work_mem
#VACUUM
# more params set in vars/main.yml
hot_standby: on
# Enable WAL file archiving
archive_mode: always
archive_command: '/bin/true'
checkpoint_timeout: 30min
checkpoint_warning: 30s
max_wal_size: 5GB
checkpoint_completion_target: 0.7
effective_cache_size: 8GB

max_wal_senders:  10
max_replication_slots: 10
wal_level: 'logical'

# 限制长事务对数据库影响
idle_in_transaction_session_timeout: '1h'
old_snapshot_threshold: '6h'

# 垃圾回收相关 < 具体值根据系统环境及应用场景待定
# auto_vacuum: on
# track_counts: on
# log_autovacuum_min_duration: 5min
# autovacuum_max_workers: 10
# autovacuum_naptime: 20
# autovacuum_vacuum_threshold: 
# autovacuum_analyze_threshold: 
# autovacuum_vacuum_scale_factor: 
# autovacuum_freeze_max_age: 
# autovacuum_vacuum_cost_delay:
# autovacuum_vacuum_cost_limit:


