- name: install loki
  copy:
    src: "{{local_bin}}/loki/{{ item }}"
    dest: /tmp/
    mode: '0755'
  with_items: 
    - loki.rpm

- name: install loki service
  package:
    name: /tmp/loki.rpm
    state: present