# become_user: postgres
---
### 远程下载安装包对网络环境有依赖 ， 后期考虑搭建私有镜像仓库
###

# - name: install pgdg rpm
#   become_user: root
#   yum:
#     name: http://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
#     state: present
#   tags: install

- name: install |  Setup PostgreSQL repository for {{ ansible_distribution }}
  become_user: root
  block:
  - name: Prepare PostgreSQL RPM
    copy: 
      src: "pgdg-redhat-repo-latest.noarch.rpm"
      dest: /tmp/

  - name: install |  Install PostgreSQL RPM
    package:
      name: /tmp/pgdg-redhat-repo-latest.noarch.rpm
      state: present
  when: ansible_distribution == "CentOS"

- name: install | Install PostgreSQL Service
  package: name={{ pg_base_packages }} state=present
  with_items:
    - '{{ pg_base_packages }}'
  register: install_postgresql

- name: install | Install PostgreSQL Base Extensions Packages
  package: name={{ pg_extends_packages }} state=present
  with_items:
    - '{{ pg_extends_packages }}'
  
- name: install | make postgres data dir
  file:
    path: "{{PG_DATA}}"
    state: directory
    owner: postgres
    group: postgres
    mode: 0700

- name: install | Prepare Config PostgreSQL Serivice 
  file:
    path: /etc/systemd/system/postgresql-{{PG_VERSION}}.service.d
    state: directory

- name: install | Config PostgreSQL Serivice 
  template:
    dest: /etc/systemd/system/postgresql-{{PG_VERSION}}.service.d/pg_service.conf
    src: postgresql-{{PG_VERSION}}_service.conf.j2
         