############################################################
#        判断数据库DATA是否已经存在                            #
############################################################
- import_tasks: validate.yml

############################################################
#        安装数据库服务包                                     #
############################################################
- include: install.yml
  when: need_init_db|bool
  tags: install
###########################################################
#        原生主从流复制                                     #
###########################################################
##       主库初始化数据库
- include: initdb.yml
  when: replicaof is undefined and need_init_db|bool
  tags: initdb
##       从库复制数据
- include: replication.yml
  when: replicaof is defined and need_init_db|bool
  tags: initdb
  
- import_tasks: tunning.yml
###########################################################
#        监控数据                                          #
###########################################################
- import_tasks: monitor.yml