############################################################
#        判断数据库DATA是否已经存在                            #
############################################################
- name: check if postgres data exists.
  stat:
    path: "{{PG_DATA}}/PG_VERSION"
  register: stat_result

- name: set if need initdb var
  set_fact:
     need_init_db : "{{ not stat_result.stat.exists}}"

- name: Print init DB Messages
  debug:
    msg: "数据库需要初始化数据: {{ need_init_db }}"
