- name: gencert etcd
  delegate_to: localhost
  block:
    - name: create certs dir
      file:
        path: "{{ CERT_LOCAL_DIR }}/etcd" 
        state: directory 
        mode: 0755 
      run_once: true

    - name: generate etcd private key
      openssl_privatekey:
        path: "{{ CERT_LOCAL_DIR }}/etcd/etcd-{{ inventory_hostname }}-key.pem"
        mode: 0644

    - name: generate etcd signing request
      openssl_csr:
        path: "{{ CERT_LOCAL_DIR }}/etcd/etcd-{{ inventory_hostname }}.csr"
        privatekey_path: "{{ CERT_LOCAL_DIR }}/etcd/etcd-{{ inventory_hostname }}-key.pem"
        common_name: "etcd-{{ inventory_hostname }}"
        organization_name: tea
        organizational_unit_name: etcd
        force: true
        subject_alt_name:
          - IP:127.0.0.1
          - DNS:localhost
          - "IP:{{ inventory_hostname }}"
          - "DNS:etcd-{{ inventory_hostname }}"

    - name: issue etcd server certificate
      openssl_certificate:
        path: "{{ CERT_LOCAL_DIR }}/etcd/etcd-{{ inventory_hostname }}-crt.pem"
        csr_path: "{{ CERT_LOCAL_DIR }}/etcd/etcd-{{ inventory_hostname }}.csr"
        ownca_path: "{{ CERT_LOCAL_DIR }}/ca.crt"
        ownca_privatekey_path: "{{ CERT_LOCAL_DIR }}/ca-key.pem"
        provider: ownca
        selfsigned_not_after: "+{{ CERT_EXPIRY }}"
        mode: 0644