--- 
- import_tasks: node_prepare.yml
  tags: always

- import_tasks: gencert.yml
  tags: [gencert, install] 

- import_tasks: install_etcd.yml
  tags: install

## 当场景为 添加新节点时 
- import_tasks: add_etcd.yml
  tags: [add]
  when: playbook_action="add_etcd"

- import_tasks: start_etcd.yml
  tags: [install, start]

- import_tasks: tuning_etcd.yml
  tags: [install, tuning]
