- name: prepare loki 
  copy:
    src: "{{local_bin}}/loki/{{ item }}"
    dest: /tmp/
    mode: '0755'
  with_items: 
    - loki.deb

- name: install loki service
  apt:
    deb: /tmp/loki.deb
  notify: event_stop_loki
  

