- name: restart prometheus
  service: name=prometheus state=restarted enabled=yes daemon_reload=yes

- name: event_restart_grafana
  service:
    name: grafana-server
    enabled: true
    state: restarted