---

- name: yum | Install PgBouncer
  yum:
    name: "pgbouncer"
    state: installed

- name: Backup pgbouncer config
  copy:
    src: /etc/pgbouncer/pgbouncer.ini
    dest: /etc/pgbouncer/pgbouncer.ini.bak
    owner: pgbouncer
    group: pgbouncer
    remote_src: yes

- name: systemd pgbouncer override number open file limit 1
  file:
    path: /etc/systemd/system/pgbouncer.service.d/
    state: directory
    owner: pgbouncer
    group: pgbouncer

- name: systemd pgbouncer override number open file limit 2
  template:
    dest: /etc/systemd/system/pgbouncer.service.d/pgb.conf
    src: pgb.conf.j2
    handlers: Restart PgBouncer

- name: config pgbouncer 
  template:
    src: pgbouncer.ini.j2
    dest: /etc/pgbouncer/pgbouncer.ini
    owner: pgbouncer
    group: pgbouncer
# - name: config postgres hostname for pgbench master
#   replace:
#     path: /etc/pgbouncer/pgbouncer.ini
#     regexp: 'POSTGRES_HOSTNAME_PLACEHOLDER'
#     replace: "{{ postgres_master }}"

- name: config postgres hostname 
  replace:
    path: /etc/pgbouncer/pgbouncer.ini
    regexp: 'POSTGRES_HOSTNAME_PLACEHOLDER'
    replace: "127.0.0.1"

- name: Touch userlist.txt file
  file:
    path: /etc/pgbouncer/userlist.txt
    state: touch
    group: pgbouncer
    owner: pgbouncer
    mode: 0666

- name: pgbouncer hba 
  template:
    dest: /etc/pgbouncer/pgb_hba.conf
    src: pgb_hba.conf.j2
    group: pgbouncer
    owner: pgbouncer
    mode: 0644

# - name: makauth file
#   copy:
#     dest: /etc/pgbouncer/mkauth.py
#     src: mkauth.py
#     group: pgbouncer
#     owner: pgbouncer
#     mode: 0755

- name: makauth file
  file:
    path: /etc/pgbouncer/mkauth.py
    group: pgbouncer
    owner: pgbouncer
    mode: 0755

- name: Sync Postgresql users to pgbouncer
  shell: | 
    python /etc/pgbouncer/mkauth.py /etc/pgbouncer/userlist.txt  "host=localhost user=postgres"
  become_user: root

- name: Start PgBouncer
  service:
    name: pgbouncer
    state: started
    enabled: yes

- name: wait for pgbouncer service starting
  wait_for:
    port: 6432
    state: started  

- name: set pgbouncer admin alias
  copy: 
    dest: /etc/profile.d/pgb.sh
    src: pgb.sh
    mode:  0777