- name: 安装redis
  yum: name=/tmp/redis.rpm state=latest

- name: install python-redis
  yum: name=python-redis state=present

- name: 配置 redis
  template: 
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    owner: redis
    group: redis

- name: redis 启动服务
  service: 
    name: redis
    state: restarted
    enabled: true
    daemon_reload: yes

- name: redis 等待服务启动
  wait_for: 
    port: 6379
    state: started

  