###
- include: prepare.yml
  tags: always

## sentinel 相关
- include: sentinel.yml
  tags: sentinel

  # 安装 redis
- include: install_redis.yml
  tags: redis
  # redis 主从 复制， 在从节点执行
- include: slaveof.yml
  tags: redis
  
- include: register.yml
  tags: redis

## 监控 相关
- include: monitor.yml
  tags: monitor
