###
- include: prepare.yml
  tags: always

  # 安装 redis, 包括主从
- include: install_redis.yml
  tags: redis
  # redis 主从 复制， 在从节点执行

- include: user.yml
  tags: user

# sentinel 相关
- include: sentinel.yml
  tags: sentinel

## 监控 相关
- include: monitor.yml
  tags: monitor
