
## sentinel 相关
- block:
  - include: sentinel.yml
  when: action == 'sentinel'
  tags: sentinel

- block:
  # 安装 redis
    - include: install.yml
  # redis 主从
    - include: slaveof.yml
    - include: register.yml
  when: action == 'redis'
  tags: redis

## 监控 相关
- include: monitor.yml
  when: action == 'monitor'
  tags: monitor

- include: install.yml
  when: action == 'install'
  tags: install