- name: redis moinitor
  block:
    - name: prepare redis exporter
      copy:
        src: "{{ local_bin }}/redis_exporter/redis_exporter"
        dest: /usr/local/bin/redis_exporter
        mode: 0755

    - name: config redis exporter 01
      template: 
        src: redis_exporter.service.j2
        dest: /usr/lib/systemd/system/redis_exporter.service


    - name: config redis exporter 02
      template: 
        src: redis_exporter.j2
        dest: /etc/default/redis_exporter


    - name: start redis exporter
      service: name=redis_exporter state=restarted daemon_reload=yes enabled=true

    - name: wait for redis exporter
      wait_for:
        port: 9121
        state: started

    - name: mkdir prometheus redis
      file: 
        path: /etc/prometheus/redis
        state: directory

                 
    - name: genrate discovery redis tmp
      copy:
        dest: /etc/prometheus/redis/discovery-redis.tmp
        content: |
          #########################################################################redis#######################################
            - job_name: 'redis_exporter_targets'
              file_sd_configs:
                - files:
                  - /etc/prometheus/redis/*.json
              metrics_path: /scrape
              relabel_configs:
                - source_labels: [__address__]
                  target_label: __param_target
                - source_labels: [__param_target]
                  target_label: instance
                - target_label: __address__
                  replacement: 127.0.0.1:9121

            - job_name: 'redis_exporter'
              static_configs:
                - targets:
                  - 127.0.0.1:9121
          
    - name: discovery redis
      shell: |
        result=$(cat /etc/prometheus/prometheus.yml | grep redis_exporter_targets)
        if [[ "$result" == "" ]]
        then
          cat /etc/prometheus/redis/discovery-redis.tmp >> /etc/prometheus/prometheus.yml
        fi

    - name: add redis targets
      copy:
        dest: /etc/prometheus/redis/{{ item }}.json
        content: |
          [
            {
              "targets": [ "redis://{{ item }}:6379"],
              "labels": { "instance": "{{ item }}" }
            }
          ]
      with_items: "{{ groups['redis'] }}"

    - name: restart prometheus
      systemd: name=prometheus state=restarted enabled=yes daemon_reload=yes
      tags: monitor
      
    - name: "Check if prometheus is accessible."
      uri:
        url: http://127.0.0.1:9090
        method: GET
        status_code: 200
      tags: monitor

    - name: load redis dashboard json
      copy:
        dest: /var/lib/grafana/dashboards/
        src: dashboards/redis
        owner: grafana
        group: grafana

    - name: load redis alert yml
      copy:
        dest: /etc/prometheus/rules/
        src: rules/redis_alert.yml

  run_once: true
  tags: monitor