  - name: 将主从复制的主节点注册到sentinel 中
    shell: | 
      redis-cli -h {{ item }} -p 26379 -a {{ sentinel_password }} SENTINEL monitor {{ master_groupname }} {{ inventory_hostname }} {{ redis_port}}  {{ quorum }} 
      redis-cli -h {{ item }} -p 26379 -a {{ sentinel_password }} SENTINEL set {{ master_groupname }}  auth-pass  {{ redis_password }}
      redis-cli -h {{ item }} -p 26379 -a {{ sentinel_password }} SENTINEL set {{ master_groupname }}  down-after-milliseconds  {{ down_after_milliseconds }}
      redis-cli -h {{ item }} -p 26379 -a {{ sentinel_password }} SENTINEL set {{ master_groupname }}  failover-timeout  {{ failover_timeout }}
      redis-cli -h {{ item }} -p 26379 -a {{ sentinel_password }} SENTINEL set {{ master_groupname }}  parallel-syncs  {{ parallel_syncs }}
    when: redis_role is defined and redis_role == 'master'
    delegate_to: "{{ item }}"
    with_items: "{{ groups['redis_sentinel'] }}"
    tags: sentinel