- name: 安装 redis-sentinel
  package: name=/tmp/redis.rpm state=latest  

- name: 配置 sentinel
  template: 
    src: sentinel.conf.j2
    dest: /etc/redis/sentinel.conf
    owner: redis
    group: redis

- name: sentinel 启动服务
  service: 
   name: redis-sentinel
   state: restarted
   daemon_reload: yes
   enabled: true

- name: sentinel 等待服务启动成功
  wait_for:
   state: started
   port: "{{sentinel_port}}"

