# 认证连接主服务信息
# - name: replication masterauth
#   redis:
#    command: config
#    name: masterauth
#    value: "{{ redis_password }}"
#    login_port: "{{ redis_port }}"
#    login_password: "{{ redis_password }}"

# - name: slave role
#   set_fact:
#     slave_mode: master
#   when: inventory_hostname == master_node

# 执行replicaof
# - name: replicaof ip port
#   redis:  
#     command: slave
#     master_host: "{{ master_node }}"
#     master_port: "{{ redis_port }}"
#     login_password: "{{ redis_password }}"
#     login_port: "{{ redis_port }}"
#     slave_mode: "{{ slave_mode }}"

- name: replicaof test
  shell: |
    echo "1"

- name: replicaof 主从复制
  shell: | 
   redis-cli --user replica-user --askpass "{{ redis_password }}" -p "{{ redis_port }}" --tls --cert /etc/redis/certs/redis.crt --key /etc/redis/certs/redis.key --cacert /etc/redis/certs/ca.crt replicaof {{ master_node}}
   redis-cli --user replica-user --askpass "{{ redis_password }}" -p "{{ redis_port }}" --tls --cert /etc/redis/certs/redis.crt --key /etc/redis/certs/redis.key --cacert /etc/redis/certs/ca.crt config rewrite
  tags: master_replica


