- alert: MinioClusterDiskOffline
  expr: minio_cluster_disk_offline_total > 0
  for: 0m
  labels:
    severity: critical
  annotations:
    summary: Minio cluster disk offline (instance {{ $labels.instance }})
    description: "Minio cluster disk is offline\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

- alert: MinioNodeDiskOffline
  expr: minio_cluster_nodes_offline_total > 0
  for: 0m
  labels:
    severity: critical
  annotations:
    summary: Minio node disk offline (instance {{ $labels.instance }})
    description: "Minio cluster node disk is offline\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

- alert: MinioDiskSpaceUsage
  expr: disk_storage_available / disk_storage_total * 100 < 10
  for: 0m
  labels:
    severity: warning
  annotations:
    summary: Minio disk space usage (instance {{ $labels.instance }})
    description: "Minio available free space is low (< 10%)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

- alert: NodesOffline
  expr: avg_over_time(minio_cluster_nodes_offline_total{job="minio-job"}[5m]) > 0
  for: 10m
  labels:
    severity: warn
  annotations:
    summary: "Node down in MinIO deployment"
    description: "Node(s) in cluster {{ $labels.instance }} offline for more than 5 minutes"

- alert: DisksOffline
  expr: avg_over_time(minio_cluster_disk_offline_total{job="minio-job"}[5m]) > 0
  for: 10m
  labels:
    severity: warn
  annotations:
    summary: "Disks down in MinIO deployment"
    description: "Disks(s) in cluster {{ $labels.instance }} offline for more than 5 minutes"