# - name: install libevent-dev
#   package: 
#     name:  libevent-devel
#     state: latest
#   tags: install

- name: create user memcached
  user:
    name: "{{ MEMCACHED_USER }}"
    create_home: no
    shell: /sbin/nologin
  tags: install

- name: install memcached , prepare binary package
  copy: 
    src: "{{ local_bin }}/memcached/memcached"
    dest: /usr/local/bin/memcached
    mode: '0755'
  tags: install


- name: install memcached -- config serivce
  template: 
    src: memcached.service.j2
    dest: /usr/lib/systemd/system/memcached.service  
  notify: restart memcached
  tags: install


- name: install memcached -- config memcached conf
  template: 
    src: memcached.j2
    dest: /etc/sysconfig/memcached
  notify: restart memcached
  tags: install

- name: start serivce memcached
  systemd:  
    name: memcached
    state: started
    enabled: yes
    daemon_reload: yes

- name: wait for memcached serivce up
  wait_for:
    port: "{{ MEMCACHED_PORT }}"
    state: started
