{
 "title": "系统报警信息",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Blackbox",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "BlackboxProbe",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    { "expr": "Blackbox:Probe" }
   ]
  },
  {
   "title": "实例基本信息",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "实例存活状态",
     "type": "table-old",
     "gridPos": { "h": 5, "w": 20, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "up{job=\"system\"}",
       "legendFormat": "{{idc}}_{{instance}}"
      }
     ]
    },
    {
     "title": "实例整体状态",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 8 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "count_values('value',up{job=\"system\"})",
       "legendFormat": "{{value}}"
      }
     ]
    },
    {
     "title": "CUP使用率",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "100 - (avg by (instance)(irate(node_cpu_seconds_total{mode=\"idle\"}[1m]) )) * 100",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "内存使用率",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(node_memory_MemTotal_bytes - (node_memory_MemFree_bytes+node_memory_Buffers_bytes+node_memory_Cached_bytes )) / node_memory_MemTotal_bytes * 100",
       "legendFormat": "{{idc}}_{{instance}}"
      }
     ]
    },
    {
     "title": "IO  wait",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (idc,instance)(irate(node_cpu_seconds_total{mode=\"iowait\"}[1m])) * 100",
       "legendFormat": "{{idc}}_{{instance}}"
      }
     ]
    },
    {
     "title": "磁盘容量",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(node_filesystem_size_bytes - node_filesystem_avail_bytes) / node_filesystem_size_bytes * 100",
       "legendFormat": "{{idc}}_{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "证书",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "证书剩余时间",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "(probe_ssl_earliest_cert_expiry{job=\"blackbox_http_2xx\"} - time())/84000"
      }
     ]
    }
   ]
  }
 ]
}