#!/usr/bin/env ansible-playbook
- hosts: "etcd"
  gather_facts: no
  pre_tasks:
    - name: validate
      block:
      - name: validate etcd cluster name 
        assert:
          that:
            - ETCD_NAME is defined
          fail_msg: variable 'ETCD_NAME' should be defined

      - name: test
        connection: local
        debug:
          msg: "etcd cluster name : {{ ETCD_NAME }}"
      
      - name: Task name
        stat:
          path: "{{ ETCD_DATA_DIR }}/member"
        register: register_member_dir

      # 如果新节点数据中遗留 旧集群数据，将会造成新旧集群节点member混乱。整个集群将挂掉。  panic: failed to update; member unknown
      - name: 新节点数据目录是否为空
        fail: 
          msg: "{{ ETCD_DATA_DIR }}/member 已存在 ！"
        when: register_member_dir.stat.exists and register_member_dir.stat.isdir
        
      run_once: true 

  vars:
    CERT_LOCAL_DIR: "{{CERT_LOCAL_BASE_DIR}}/{{ ETCD_NAME }}"
    CLUSTER_STATE: existing
    
  roles:
      - { role: ca ,tags: ca}
      - { role: etcd, tags: etcd }

  post_tasks:
    - name: ETCD 集群状态收集
      shell:
        etcdctl endpoint health
      register: etcd_health_result

    - name: ETCD 集群状态查看  
      debug:
        msg: "{{etcd_health_result.stdout}}"