- hosts: "etcd"
  gather_facts: no
  pre_tasks:
    - name: validate
      block:
      - name: validate etcd cluster name 
        assert:
          that:
            - NAME is defined
          fail_msg: variable 'NAME' should be defined
      - name: test
        connection: local
        debug:
          msg: "etcd cluster name : {{ NAME }}"
      run_once: true 
  vars:
    CERT_LOCAL_DIR: "/etc/tealabs/etcd/{{ NAME }}"
    CLUSTER_STATE: existing
  roles:
      - { role: ca }
      - { role: etcd }