#!/usr/bin/env ansible-playbook
- hosts: "{{ server_name | default('pg_patroni')}}"
  # any_errors_fatal: true
  roles: 
    - { role: patroni ,tags patroni}

  post_tasks:
    - name: patroni 集群状态收集
      get_url:
        url: http://{{inventory_hostname}}:8008/health
        dest: /tmp/
      register: patroni_health_result

    - name: patroni 集群状态查看  
      debug:
        msg: "{{patroni_health_result.status_code}}"
