#!/usr/bin/env ansible-playbook
## redis sentinel 服务
- hosts: redis
  gather_facts: true
  vars:
      CERT_LOCAL_DIR: "{{ CERT_LOCAL_BASE_DIR }}/redis"
  roles:
    - { role: ca ,only_common_cert: true}
    - { role: redis }

## 监控redis 
# - hosts: monitor
#   roles:
#    - { role: redis ,action: monitor,tags: 'monitor'} 
#    - { role: monitor, only_load_dashboard: true,tags: 'monitor' }