#!/usr/bin/env ansible-playbook
---
- hosts: nginx
  roles: 
    - { role: node, server: nginx }
    - { role: nginx }

# https://grafana.com/grafana/dashboards/12559-grafana-loki-dashboard-for-nginx-service-mesh/