#!/usr/bin/env ansible-playbook
---
- hosts: minio
  tasks:
    - name: stop minio
      systemd: name=minio state=stopped enabled=no

    - name: stop sidekick
      systemd: name=sidekick state=stopped enabled=no
    
    - name: clean data dir
      file:
        path: "{{ item }}"
        state: absent
      with_items: 
        - "{{ NODE_DIR }}"
    
    - name: clean conf 
      file: 
        path: "{{ item  }}"
        state: absent
      with_items:
        - "/etc/default/minio"  
        - "/etc/systemd/system/minio.service"
        - "/usr/local/bin/mc"
        - "/usr/local/bin/minio"
        - "/usr/local/bin/sidekick"
    
    - name: clean hosts dns
      lineinfile:
        path: /etc/hosts
        regexp: "minio(.*)"
        state: absent 