#!/usr/bin/env ansible-playbook
- hosts: monitor 
  become: yes
  become_method: sudo
  roles: 
##--------主要流程及内容---------------------------------------
# 一， 服务器基础配置，必要软件安装
# 二， 安装监控服务
# 三， 安装 node_exporter blackbox_exporter
# 四， 载入dashboard 到grafana 
##-----------------------------------------------
    - { role: monitor }
