#!/usr/bin/env ansible-playbook
---
- hosts: nodes
  gather_facts: true
  become: yes
  become_method: sudo
  roles: # node init config
  - role: node 

# - hosts: logs
#   roles: # promtail collect sys log
#   - role: promtail