#!/usr/bin/env ansible-playbook
---
- hosts: nodes
  gather_facts: true
  become: yes
  become_method: sudo
  roles: # node init config
  - role: node 

#!/usr/bin/env ansible-playbook
- hosts: monitor 
  become: yes
  become_method: sudo
  roles: 
    - { role: monitor }
  when: node_monitor | default(false)
  

# - hosts: logs
#   roles: # promtail collect sys log
#   - role: promtail