#!/usr/bin/env ansible-playbook
---
- hosts: nodes
  # gather_facts: false
  roles: # node init config
  - role: node 
    when: inventory_hostname not in groups['monitor']

- hosts: logs
  roles: # promtail collect sys log
  - role: promtail