#!/usr/bin/env ansible-playbook
---
- hosts: nodes
  gather_facts: false
  remote_user: "{{ username }}"
  # become: yes
  # become_method: sudo
  # vars:
  #  repo = use
  roles: 
  - {role: repo ,repo : use}