# 更新
- name: Update all packages to the latest version
  apt:
    update_cache: yes

- name: Update all packages to the latest version
  apt:
    upgrade: dist

# ulimit -n 限制设置

- name: update /etc/security/limits.conf 永久有效
  tags: ulimit
  blockinfile:
    dest: /etc/security/limits.conf
    insertbefore: '# End of file'
    block: |
      * - nofile 655360
      * soft nproc 655360
      * hard nproc 655360
      * soft nofile 655360
      * hard nofile 655360

# 设置 hostname
- name: set hostname and /etc/hosts
  block: 
    - name: fetch old hostname
      shell: 
        hostname
      register: oldhostname
    # - debug:
    #     msg: "{{ oldhostname.stdout }}"
    # - name: set /etc/hosts1
    #   lineinfile:
    #     path: /etc/hosts
    #     regexp: '^127.0.0.1 {{ oldhostname.stdout }}'
    #     state: absent

    - name: set /etc/hosts
      lineinfile: 
        path: /etc/hosts
        line: "127.0.0.1 {{ hostname }}"
        regexp: "^127.0.0.1	{{ oldhostname.stdout }}"
        # firstmatch: yes
        state: present
    - name: set hostname 
      hostname: 
        name: "{{ hostname }}"
  when: hostname is defined and hostname != 'localhost'
  tags: hostname

# 网络同步时间
- name: chrony 同步网络时间
  block:
  - name: chrony install
    package: name=chrony state=latest 

  - name: start chrony server
    systemd: name=chronyd state=restarted enabled=yes daemon_reload=yes

- name: sysctl 配置
  sysctl:
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
    ignoreerrors: yes
  with_dict: '{{ sysctl_config }}'

- name: 安装常用工具
  package:
    name:
      - vim
      - ufw 
      - net-tools
      - telnet
      - iputils-ping
    state: present

# 防火墙管理
- name: 开启服务，开机自启
  ufw: 
    state: enabled

- name: ssh 开放
  ufw:
    rule: allow
    name: OpenSSH

- name: ssh limit
  ufw:
    rule: limit
    port: ssh
    proto: tcp

- name: Allow all access from RFC1918 networks to this host
  ufw:
    rule: allow
    src: '{{ item }}'
  loop:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16

- name: 防火墙设置
  ufw: 
    logging: 'on'
    default: deny

