- include_tasks: 
    file: "harden.yml"
    apply:
      tags: [harden]
  tags: always
  when: harden is defined and harden == true
  
- include_tasks: 
    file: "monitor.yml"
    apply:
      tags: monitor
  tags: always
  when: monitor is defined and monitor == true