- task: install sysbench
  package: name=sysbench state=present
# https://blog.csdn.net/squirrel100/article/details/120290746
# 测试 CPU
# 

# 测试内存
# sysbench --threads=8 --time=60 --report-interval=1 --test=memory --memory-block-size=8K --memory-total-size=100G --memory-access-mode=seq run

# 测试 IO

# 线程数=4 每隔4s输出一次结果 测试时间=60s
# 文件数=2 文件总大小=4G 文件操作模式=随机读写
# 块大小 16384
#sysbench --threads=4 --report-interval=4 --time=60 --test=fileio --file-num=2 --file-total-size=4G --file-test-mode=rndrw prepare

#sysbench --threads=4 --report-interval=4 --time=60 --test=fileio --file-num=2 --file-total-size=4G --file-test-mode=rndrw run

#sysbench --threads=4 --report-interval=4 --time=60 --test=fileio --file-num=2 --file-total-size=4G --file-test-mode=rndrw cleanup
