{
 "title": "Postgres Cluster",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "集群名称",
    "query": "label_values({job=\"postgres\"}, cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "Version",
   "type": "stat",
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(pg_settings_server_version_num{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance)(pg_database_size{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Age",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(pg_database_age{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "集群信息",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "3-pg_in_recovery{cluster=\"$cluster\"}"
    },
    {
     "expr": "pg_up{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Max Replication Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_replication_data_lag{cluster=\"$cluster\"}"
    }
   ]
  }
 ]
}