{
 "title": "网络联通状况",
 "description": "blackbox_exporter 0.16.0 / 2019-11-11",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "网络延迟时间",
   "type": "graph",
   "gridPos": { "h": 14, "w": 14, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{job!=\"blackbox_http_2xx\"}",
     "legendFormat": "{{instance}} -> {{ping_to}}"
    }
   ]
  },
  {
   "title": "连通性",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": " count_values('value',probe_success{job!=\"blackbox_http_2xx\"})",
     "legendFormat": "{{ value }}"
    }
   ]
  },
  {
   "title": "状态码",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count_values('value',probe_http_status_code{job=\"blackbox_http_2xx\"})",
     "legendFormat": "{{ value }}"
    }
   ]
  },
  {
   "title": "阶段延迟耗时",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_icmp_duration_seconds",
     "legendFormat": "{{instance}} -> {{ping_to}} {{phase}}"
    },
    {
     "expr": "sum by (phase) (probe_icmp_duration_seconds)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "状态明细",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "probe_http_ssl{job=\"blackbox_http_2xx\"} - 0"
    },
    {
     "expr": "probe_http_status_code{job=\"blackbox_http_2xx\"} - 0"
    },
    {
     "expr": "probe_ssl_earliest_cert_expiry{job=\"blackbox_http_2xx\"} - time()"
    }
   ]
  }
 ]
}