# TODO 二进制文件方式安装
- name: create group etcd
  group: name="etcd"  system=no
- name: create user etcd 
  user:
    name: etcd
    create_home: no
    home: /var/lib/etcd/
    shell: /sbin/nologin
    group: etcd

- name: copy etcd binaries
  copy:
    dest: /usr/bin/
    src: "{{ local_bin }}/etcd/{{item}}"
    owner: etcd
    group: etcd
    mode: 0755
  with_items:
    - etcd
    - etcdctl
    - etcdutl

- name: make data directory 
  file:
    path: "{{ item }}"
    state: directory
    owner: etcd
    group: etcd
  with_items:
    - "/etc/etcd" 
    - "{{ ECTD_CERT_DIR }}"
    - "{{ ETCD_WAL_DIR }}"

- name: 分发etcd证书
  block:
  - name: Distribute ca.pem
    copy: src={{ CERT_LOCAL_DIR }}/ca.pem dest={{ECTD_CERT_DIR}}/etcd-ca.pem
  - name: Distribute etcd-key.pem
    copy: src={{ CERT_LOCAL_DIR }}/{{ inventory_hostname }}-key.pem dest={{ECTD_CERT_DIR}}/etcd-key.pem
  - name: Distribute etcd.pem
    copy: src={{ CERT_LOCAL_DIR }}/{{ inventory_hostname }}-crt.pem dest={{ECTD_CERT_DIR}}/etcd.pem
  tags: etcd_csr

# etcd 服务配置文件
- name: 创建etcd的systemd unit文件
  template: src=etcd.service.j2 dest=/etc/systemd/system/etcd.service
  tags: upgrade_etcd, restart_etcd

- name: 创建etcd的 conf 文件
  template: src=etcd.conf.j2 dest=/etc/etcd/etcd.conf
  tags: upgrade_etcd, restart_etcd


- name: write etcd environment profile
  tags: etcd_env
  copy:
    dest: /etc/profile.d/etcdctl.sh
    mode: 0644
    content: |
      #!/bin/bash
      alias es="etcdctl endpoint status --cluster -w table"
      export ETCDCTL_API=3
      export ETCDCTL_ENDPOINTS="https://{{ inventory_hostname }}:{{ ETCD_CLIENT_PORT }}"
      export ETCDCTL_CACERT={{ECTD_CERT_DIR}}/etcd-ca.pem
      export ETCDCTL_CERT={{ECTD_CERT_DIR}}/etcd.pem
      export ETCDCTL_KEY={{ECTD_CERT_DIR}}/etcd-key.pem