--- 
- import_tasks: node_prepare_debian.yml
  when: ansible_os_family == 'Debian'
  tags: always

- import_tasks: node_prepare_redhat.yml
  when: ansible_os_family == 'RedHat'
  tags: always

- import_tasks: install_etcd.yml
  tags: install

## 当场景为 添加新节点时 
- import_tasks: add_etcd.yml
  tags: [add]
  when: CLUSTER_STATE=="existing"

- import_tasks: start_etcd.yml
  tags: [install, start]

- import_tasks: tuning_etcd.yml
  tags: [install, tuning]

- import_tasks: monitor.yml
  # delegate_to: 
  tags: monitor
